version: '3.9'

services:
  redis:
    container_name: cache
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
    networks:
      - nest-init
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/var/lib/mongodb/data
    ports:
      - '27017:27017'
    networks:
      - nest-init

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq/data

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    networks:
      - nest-init

#  pgadmin:
#    image: dpage/pgadmin4
#    restart: always
#    container_name: nest-pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
#    ports:
#      - '5050:80'
#    depends_on:
#      - postgres
#      - redis

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-project-template
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
      - mongo
      - rabbitmq
    volumes:
      - ./src:/app/src
    networks:
      - nest-init
volumes:
  postgres-data:
  redis:
    driver: local
  mongo-data:
  rabbitmq:

networks:
  nest-init:
    driver: bridge